/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the testflow file being used. In the 
 * SmarTest Work Center, you can navigate to the generating source 
 * by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over either of these two file paths listed below:
 * 
 *   1. The test method location which resulted in the creation of this file:
 *      src/sparatest/SPara.java:63
 * 
 *   2. The testflow file which contains the used test suite and parameter
 *      settings:
 *      LNA/src/sparatest/sParaFlow.flow
 * 
 *      The name of the test suite is: Main.RF_FT.Sparm.sParameterTest
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
spec Spec_1
{
    action sPara_1500000000;
    action sPara_1510000000;
    action sPara_1520000000;
    action sPara_1530000000;
    action sPara_1540000000;
    action sPara_1550000000;
    action sPara_1560000000;
    action sPara_1570000000;
    action sPara_1580000000;
    action sPara_1590000000;
    action sPara_1600000000;
    action sPara_1610000000;
    action sPara_1620000000;
    action sPara_1630000000;
    action sPara_1640000000;
    action sPara_1650000000;
    action sPara_1660000000;
    action sPara_1670000000;
    action sPara_1680000000;
    action sPara_1690000000;
    action sPara_1700000000;
    action sPara_1710000000;
    action sPara_1720000000;
    action sPara_1730000000;
    action sPara_1740000000;
    action sPara_1750000000;
    action sPara_1760000000;
    action sPara_1770000000;
    action sPara_1780000000;
    action sPara_1790000000;
    action sPara_1800000000;
    action sPara_1810000000;
    action sPara_1820000000;
    action sPara_1830000000;
    action sPara_1840000000;
    action sPara_1850000000;
    action sPara_1860000000;
    action sPara_1870000000;
    action sPara_1880000000;
    action sPara_1890000000;
    action sPara_1900000000;
    action sPara_1910000000;
    action sPara_1920000000;
    action sPara_1930000000;
    action sPara_1940000000;
    action sPara_1950000000;
    action sPara_1960000000;
    action sPara_1970000000;
    action sPara_1980000000;
    action sPara_1990000000;
    action sPara_2000000000;
    action sPara_2010000000;
    action sPara_2020000000;
    action sPara_2030000000;
    action sPara_2040000000;
    action sPara_2050000000;
    action sPara_2060000000;
    action sPara_2070000000;
    action sPara_2080000000;
    action sPara_2090000000;
    action sPara_2100000000;
    action sPara_2110000000;
    action sPara_2120000000;
    action sPara_2130000000;
    action sPara_2140000000;
    action sPara_2150000000;
    action sPara_2160000000;
    action sPara_2170000000;
    action sPara_2180000000;
    action sPara_2190000000;
    action sPara_2200000000;
    action sPara_2210000000;
    action sPara_2220000000;
    action sPara_2230000000;
    action sPara_2240000000;
    action sPara_2250000000;
    action sPara_2260000000;
    action sPara_2270000000;
    action sPara_2280000000;
    action sPara_2290000000;
    action sPara_2300000000;
    action sPara_2310000000;
    action sPara_2320000000;
    action sPara_2330000000;
    action sPara_2340000000;
    action sPara_2350000000;
    action sPara_2360000000;
    action sPara_2370000000;
    action sPara_2380000000;
    action sPara_2390000000;
    action sPara_2400000000;
    action sPara_2410000000;
    action sPara_2420000000;
    action sPara_2430000000;
    action sPara_2440000000;
    action sPara_2450000000;
    action sPara_2460000000;
    action sPara_2470000000;
    action sPara_2480000000;
    action sPara_2490000000;
    action sPara_2500000000;
    action sPara_2510000000;
    action sPara_2520000000;
    action sPara_2530000000;
    action sPara_2540000000;
    action sPara_2550000000;
    action sPara_2560000000;
    action sPara_2570000000;
    action sPara_2580000000;
    action sPara_2590000000;
    action sPara_2600000000;
    action sPara_2610000000;
    action sPara_2620000000;
    action sPara_2630000000;
    action sPara_2640000000;
    action sPara_2650000000;
    action sPara_2660000000;
    action sPara_2670000000;
    action sPara_2680000000;
    action sPara_2690000000;
    action sPara_2700000000;
    action sPara_2710000000;
    action sPara_2720000000;
    action sPara_2730000000;
    action sPara_2740000000;
    action sPara_2750000000;
    action sPara_2760000000;
    action sPara_2770000000;
    action sPara_2780000000;
    action sPara_2790000000;
    action sPara_2800000000;
    action sPara_2810000000;
    action sPara_2820000000;
    action sPara_2830000000;
    action sPara_2840000000;
    action sPara_2850000000;
    action sPara_2860000000;
    action sPara_2870000000;
    action sPara_2880000000;
    action sPara_2890000000;
    action sPara_2900000000;
    action sPara_2910000000;
    action sPara_2920000000;
    action sPara_2930000000;
    action sPara_2940000000;
    action sPara_2950000000;
    action sPara_2960000000;
    action sPara_2970000000;
    action sPara_2980000000;
    action sPara_2990000000;
    action sPara_3000000000;
    
    setup rfVna RF_IN1
    {
        config.port2 = RF_OUT;
    
        action sParameter sPara_1500000000
        {
            frequency = 1.5 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1510000000
        {
            frequency = 1.51 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1520000000
        {
            frequency = 1.52 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1530000000
        {
            frequency = 1.53 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1540000000
        {
            frequency = 1.54 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1550000000
        {
            frequency = 1.55 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1560000000
        {
            frequency = 1.56 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1570000000
        {
            frequency = 1.57 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1580000000
        {
            frequency = 1.58 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1590000000
        {
            frequency = 1.59 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1600000000
        {
            frequency = 1.6 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1610000000
        {
            frequency = 1.61 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1620000000
        {
            frequency = 1.62 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1630000000
        {
            frequency = 1.63 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1640000000
        {
            frequency = 1.64 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1650000000
        {
            frequency = 1.65 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1660000000
        {
            frequency = 1.66 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1670000000
        {
            frequency = 1.67 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1680000000
        {
            frequency = 1.68 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1690000000
        {
            frequency = 1.69 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1700000000
        {
            frequency = 1.7 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1710000000
        {
            frequency = 1.71 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1720000000
        {
            frequency = 1.72 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1730000000
        {
            frequency = 1.73 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1740000000
        {
            frequency = 1.74 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1750000000
        {
            frequency = 1.75 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1760000000
        {
            frequency = 1.76 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1770000000
        {
            frequency = 1.77 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1780000000
        {
            frequency = 1.78 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1790000000
        {
            frequency = 1.79 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1800000000
        {
            frequency = 1.8 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1810000000
        {
            frequency = 1.81 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1820000000
        {
            frequency = 1.82 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1830000000
        {
            frequency = 1.83 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1840000000
        {
            frequency = 1.84 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1850000000
        {
            frequency = 1.85 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1860000000
        {
            frequency = 1.86 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1870000000
        {
            frequency = 1.87 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1880000000
        {
            frequency = 1.88 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1890000000
        {
            frequency = 1.89 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1900000000
        {
            frequency = 1.9 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1910000000
        {
            frequency = 1.91 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1920000000
        {
            frequency = 1.92 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1930000000
        {
            frequency = 1.93 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1940000000
        {
            frequency = 1.94 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1950000000
        {
            frequency = 1.95 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1960000000
        {
            frequency = 1.96 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1970000000
        {
            frequency = 1.97 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1980000000
        {
            frequency = 1.98 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_1990000000
        {
            frequency = 1.99 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2000000000
        {
            frequency = 2 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2010000000
        {
            frequency = 2.01 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2020000000
        {
            frequency = 2.02 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2030000000
        {
            frequency = 2.03 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2040000000
        {
            frequency = 2.04 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2050000000
        {
            frequency = 2.05 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2060000000
        {
            frequency = 2.06 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2070000000
        {
            frequency = 2.07 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2080000000
        {
            frequency = 2.08 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2090000000
        {
            frequency = 2.09 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2100000000
        {
            frequency = 2.1 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2110000000
        {
            frequency = 2.11 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2120000000
        {
            frequency = 2.12 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2130000000
        {
            frequency = 2.13 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2140000000
        {
            frequency = 2.14 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2150000000
        {
            frequency = 2.15 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2160000000
        {
            frequency = 2.16 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2170000000
        {
            frequency = 2.17 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2180000000
        {
            frequency = 2.18 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2190000000
        {
            frequency = 2.19 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2200000000
        {
            frequency = 2.2 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2210000000
        {
            frequency = 2.21 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2220000000
        {
            frequency = 2.22 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2230000000
        {
            frequency = 2.23 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2240000000
        {
            frequency = 2.24 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2250000000
        {
            frequency = 2.25 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2260000000
        {
            frequency = 2.26 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2270000000
        {
            frequency = 2.27 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2280000000
        {
            frequency = 2.28 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2290000000
        {
            frequency = 2.29 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2300000000
        {
            frequency = 2.3 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2310000000
        {
            frequency = 2.31 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2320000000
        {
            frequency = 2.32 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2330000000
        {
            frequency = 2.33 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2340000000
        {
            frequency = 2.34 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2350000000
        {
            frequency = 2.35 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2360000000
        {
            frequency = 2.36 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2370000000
        {
            frequency = 2.37 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2380000000
        {
            frequency = 2.38 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2390000000
        {
            frequency = 2.39 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2400000000
        {
            frequency = 2.4 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2410000000
        {
            frequency = 2.41 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2420000000
        {
            frequency = 2.42 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2430000000
        {
            frequency = 2.43 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2440000000
        {
            frequency = 2.44 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2450000000
        {
            frequency = 2.45 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2460000000
        {
            frequency = 2.46 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2470000000
        {
            frequency = 2.47 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2480000000
        {
            frequency = 2.48 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2490000000
        {
            frequency = 2.49 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2500000000
        {
            frequency = 2.5 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2510000000
        {
            frequency = 2.51 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2520000000
        {
            frequency = 2.52 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2530000000
        {
            frequency = 2.53 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2540000000
        {
            frequency = 2.54 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2550000000
        {
            frequency = 2.55 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2560000000
        {
            frequency = 2.56 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2570000000
        {
            frequency = 2.57 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2580000000
        {
            frequency = 2.58 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2590000000
        {
            frequency = 2.59 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2600000000
        {
            frequency = 2.6 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2610000000
        {
            frequency = 2.61 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2620000000
        {
            frequency = 2.62 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2630000000
        {
            frequency = 2.63 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2640000000
        {
            frequency = 2.64 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2650000000
        {
            frequency = 2.65 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2660000000
        {
            frequency = 2.66 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2670000000
        {
            frequency = 2.67 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2680000000
        {
            frequency = 2.68 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2690000000
        {
            frequency = 2.69 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2700000000
        {
            frequency = 2.7 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2710000000
        {
            frequency = 2.71 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2720000000
        {
            frequency = 2.72 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2730000000
        {
            frequency = 2.73 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2740000000
        {
            frequency = 2.74 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2750000000
        {
            frequency = 2.75 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2760000000
        {
            frequency = 2.76 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2770000000
        {
            frequency = 2.77 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2780000000
        {
            frequency = 2.78 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2790000000
        {
            frequency = 2.79 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2800000000
        {
            frequency = 2.8 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2810000000
        {
            frequency = 2.81 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2820000000
        {
            frequency = 2.82 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2830000000
        {
            frequency = 2.83 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2840000000
        {
            frequency = 2.84 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2850000000
        {
            frequency = 2.85 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2860000000
        {
            frequency = 2.86 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2870000000
        {
            frequency = 2.87 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2880000000
        {
            frequency = 2.88 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2890000000
        {
            frequency = 2.89 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2900000000
        {
            frequency = 2.9 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2910000000
        {
            frequency = 2.91 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2920000000
        {
            frequency = 2.92 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2930000000
        {
            frequency = 2.93 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2940000000
        {
            frequency = 2.94 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2950000000
        {
            frequency = 2.95 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2960000000
        {
            frequency = 2.96 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2970000000
        {
            frequency = 2.97 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2980000000
        {
            frequency = 2.98 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_2990000000
        {
            frequency = 2.99 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    
        action sParameter sPara_3000000000
        {
            frequency = 3 GHz;
            stimPower = -30 dBm;
            expectedMaxPower = -15 dBm;
            bandwidthOfInterest = 50 kHz;
            resultAveraging = 1;
        }
    }
}
