/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the testflow file being used. In the 
 * SmarTest Work Center, you can navigate to the generating source 
 * by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over either of these two file paths listed below:
 * 
 *   1. The test method location which resulted in the creation of this file:
 *      src/dc_tml/DcTest/CommonCurrent.java:95
 * 
 *   2. The testflow file which contains the used test suite and parameter
 *      settings:
 *      LNA/testflows/LNA_FTA_V93K.flow
 * 
 *      The name of the test suite is: Main.OS_POST
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
import setups.specs.OS.powershort;
import setups.specs.OS.powershort;

spec VDD1P8_VDDIO_1
{
    action Imeas;
    
    setup dcVI VDD1P8
    {
        action imeas Imeas
        {
            waitTime = 2.000 ms;
            irange = 100.0000 uA;
            averages = 16;
        }
    }
    
    setup dcVI VDDIO
    {
        action imeas Imeas
        {
            waitTime = 2.000 ms;
            irange = 100.0000 uA;
            averages = 16;
        }
    }
}
