/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the testflow file being used. In the 
 * SmarTest Work Center, you can navigate to the generating source 
 * by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over either of these two file paths listed below:
 * 
 *   1. The test method location which resulted in the creation of this file:
 *      src/dc_tml/DcTest/Leakage.java:164
 * 
 *   2. The testflow file which contains the used test suite and parameter
 *      settings:
 *      LNA/testflows/POWER_UP.flow
 * 
 *      The name of the test suite is: Main.POWER_UP.IIHL
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
import setups.specs.OS.IIHL;

spec Spec_1
{
    action USID0_Low;
    action SDATA_Low;
    action SCLK_Low;
    action ATEST_Low;
    action USID0_High;
    action SDATA_High;
    action SCLK_High;
    action ATEST_High;
    
    setup digInOut USID0
    {
        action vforceImeas USID0_Low
        {
            forceValue = 0 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut SDATA
    {
        action vforceImeas SDATA_Low
        {
            forceValue = 0 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut SCLK
    {
        action vforceImeas SCLK_Low
        {
            forceValue = 0 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut ATEST
    {
        action vforceImeas ATEST_Low
        {
            forceValue = 0 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut USID0
    {
        action vforceImeas USID0_High
        {
            forceValue = 1.8 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut SDATA
    {
        action vforceImeas SDATA_High
        {
            forceValue = 1.8 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut SCLK
    {
        action vforceImeas SCLK_High
        {
            forceValue = 1.8 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
    
    setup digInOut ATEST
    {
        action vforceImeas ATEST_High
        {
            forceValue = 1.8 V;
            waitTime = 5.000 ms;
            irange = 5.000000 uA;
        }
    }
}
